#!/usr/bin/env python3
"""
description_agent/report_aggregator.py
=======================================

Aggregates per-drone description reports belonging to the same incident.

Input ROS topic:

    /description_agent/view_report
        std_msgs/String containing JSON generated by
        description_agent/inference.py

Output ROS topic:

    /description_agent/fused_report
        std_msgs/String containing one consolidated report per incident.

Reports are grouped by `incident_id`. A short configurable collection
window allows reports from multiple drones observing the same incident to
arrive before fusion.

If only one view is available, the report is passed through as a
single-view incident report.

If multiple views share the same incident_id, captions are fused using
the confidence-prioritized fusion procedure implemented in fusion.py.

For downstream severity computation, the highest-confidence primary
view supplies both:

    - YOLO confidence
    - BLIP-2 mean token log-likelihood

No artificial BLIP-2 probability is assigned to the heuristic fused text.

Usage:

    python description_agent/report_aggregator.py --ros

Optional:

    python description_agent/report_aggregator.py \
        --ros \
        --fusion-window 1.0
"""

import argparse
import json
import os
import sys
import threading
import time
from typing import Dict, List

sys.path.append(
    os.path.join(
        os.path.dirname(__file__),
        "..",
    )
)

from description_agent.fusion import (  # noqa: E402
    View,
    fuse_captions,
)
from model.utils import get_logger  # noqa: E402


logger = get_logger(
    "description_agent.aggregator"
)


class IncidentReportAggregator:
    """
    Collect and fuse per-view reports grouped by incident_id.

    One report per drone is retained for each incident during the
    collection window. If a drone submits more than one report for the
    same incident, the report with the higher YOLO confidence is retained.
    """

    def __init__(
        self,
        fusion_window_s: float = 1.0,
    ):
        if fusion_window_s < 0:
            raise ValueError(
                "fusion_window_s must be non-negative."
            )

        self.fusion_window_s = (
            fusion_window_s
        )

        self.pending: Dict[
            str,
            dict,
        ] = {}

        self.lock = threading.Lock()

    def add_report(
        self,
        report: dict,
    ) -> None:
        """
        Add one per-drone description report to the appropriate incident.
        """

        self._validate_report(
            report
        )

        incident_id = report[
            "incident_id"
        ]

        drone_id = report[
            "drone_id"
        ]

        now = time.monotonic()

        with self.lock:

            if incident_id not in self.pending:

                self.pending[
                    incident_id
                ] = {
                    "first_seen": now,
                    "reports": {},
                }

            reports = self.pending[
                incident_id
            ][
                "reports"
            ]

            existing = reports.get(
                drone_id
            )

            # Keep one report per drone. If repeated reports arrive for
            # the same incident, retain the one with higher confidence.
            if existing is None:

                reports[
                    drone_id
                ] = dict(
                    report
                )

            else:

                existing_conf = float(
                    existing.get(
                        "confidence",
                        0.0,
                    )
                )

                new_conf = float(
                    report.get(
                        "confidence",
                        0.0,
                    )
                )

                if new_conf > existing_conf:

                    reports[
                        drone_id
                    ] = dict(
                        report
                    )

                    logger.debug(
                        f"Replaced report from "
                        f"{drone_id} for "
                        f"{incident_id} because "
                        "the newer report has "
                        "higher confidence."
                    )

    def flush_ready(
        self,
        force: bool = False,
    ) -> List[dict]:
        """
        Fuse and remove incidents whose collection window has expired.

        Parameters
        ----------
        force:
            If True, flush every currently pending incident immediately.

        Returns
        -------
        list of fused report dictionaries.
        """

        now = time.monotonic()

        ready = []

        with self.lock:

            incident_ids = list(
                self.pending.keys()
            )

            for incident_id in incident_ids:

                item = self.pending[
                    incident_id
                ]

                age = (
                    now
                    - item[
                        "first_seen"
                    ]
                )

                if (
                    not force
                    and age
                    < self.fusion_window_s
                ):
                    continue

                reports = list(
                    item[
                        "reports"
                    ].values()
                )

                del self.pending[
                    incident_id
                ]

                if reports:

                    ready.append(
                        self._fuse_reports(
                            reports
                        )
                    )

        return ready

    @staticmethod
    def _validate_report(
        report: dict,
    ) -> None:
        """Validate fields required for deterministic fusion."""

        if not isinstance(
            report,
            dict,
        ):
            raise ValueError(
                "Description report must be a dictionary."
            )

        required = {
            "incident_id",
            "drone_id",
            "caption",
            "confidence",
            "log_likelihood",
        }

        missing = (
            required
            - set(
                report.keys()
            )
        )

        if missing:

            raise ValueError(
                "Description report missing required "
                f"fields: {sorted(missing)}"
            )

        if not report[
            "incident_id"
        ]:
            raise ValueError(
                "incident_id must not be empty."
            )

        if not report[
            "drone_id"
        ]:
            raise ValueError(
                "drone_id must not be empty."
            )

        if not isinstance(
            report["caption"],
            str,
        ):
            raise ValueError(
                "caption must be a string."
            )

        confidence = float(
            report["confidence"]
        )

        if (
            confidence < 0.0
            or confidence > 1.0
        ):
            raise ValueError(
                "confidence must be between 0 and 1."
            )

        float(
            report[
                "log_likelihood"
            ]
        )

    @staticmethod
    def _fuse_reports(
        reports: List[dict],
    ) -> dict:
        """
        Convert per-view reports into one consolidated incident report.
        """

        if not reports:
            raise ValueError(
                "At least one report is required."
            )

        incident_ids = {
            report[
                "incident_id"
            ]
            for report in reports
        }

        if len(
            incident_ids
        ) != 1:
            raise ValueError(
                "Cannot fuse reports with different incident_id values."
            )

        mission_ids = {
            report.get(
                "mission_id"
            )
            for report in reports
            if report.get(
                "mission_id"
            )
            is not None
        }

        if len(
            mission_ids
        ) > 1:
            raise ValueError(
                "Cannot fuse reports from different missions."
            )

        views = []

        report_by_drone = {}

        for report in reports:

            drone_id = report[
                "drone_id"
            ]

            report_by_drone[
                drone_id
            ] = report

            views.append(
                View(
                    drone_id=drone_id,
                    confidence=float(
                        report[
                            "confidence"
                        ]
                    ),
                    caption=report[
                        "caption"
                    ],
                )
            )

        fused = fuse_captions(
            views
        )

        primary_drone = fused[
            "primary_drone"
        ]

        primary_report = (
            report_by_drone[
                primary_drone
            ]
        )

        incident_types = {
            report.get(
                "incident_type"
            )
            for report in reports
            if report.get(
                "incident_type"
            )
        }

        if len(
            incident_types
        ) > 1:
            logger.warning(
                "Per-view incident-type disagreement "
                f"for {primary_report['incident_id']}: "
                f"{sorted(incident_types)}. "
                "Using the primary view's class."
            )

        # Prefer the assigned incident target because this represents
        # the incident location supplied by the planning/coordination
        # pipeline. Fall back to the drone's detection position.
        location = (
            primary_report.get(
                "assigned_target"
            )
            or primary_report.get(
                "position"
            )
            or {}
        )

        source_event_ids = [
            report.get(
                "event_id"
            )
            for report in reports
            if report.get(
                "event_id"
            )
        ]

        source_drones = [
            report[
                "drone_id"
            ]
            for report in reports
        ]

        result = {
            "mission_id": (
                primary_report.get(
                    "mission_id"
                )
            ),

            "incident_id": (
                primary_report[
                    "incident_id"
                ]
            ),

            "incident_index": (
                primary_report.get(
                    "incident_index"
                )
            ),

            "incident_type": (
                primary_report.get(
                    "incident_type",
                    "unknown",
                )
            ),

            "coordinate_mode": (
                primary_report.get(
                    "coordinate_mode",
                    "local",
                )
            ),

            "location": location,

            "summary": fused[
                "fused_caption"
            ],

            "fused_caption": fused[
                "fused_caption"
            ],

            "primary_drone": (
                primary_drone
            ),

            # These two fields are the pair used by Eq. 24.
            "severity_confidence": float(
                primary_report[
                    "confidence"
                ]
            ),

            "severity_log_likelihood": float(
                primary_report[
                    "log_likelihood"
                ]
            ),

            "primary_weight": (
                fused.get(
                    "primary_weight",
                    1.0,
                )
            ),

            "weights": fused.get(
                "weights",
                {},
            ),

            "appended_terms": (
                fused.get(
                    "appended_terms",
                    [],
                )
            ),

            "fusion_method": (
                fused.get(
                    "fusion_method",
                    "single_view",
                )
            ),

            "num_views": len(
                reports
            ),

            "source_drones": (
                source_drones
            ),

            "source_event_ids": (
                source_event_ids
            ),

            "fused_timestamp": (
                time.time()
            ),
        }

        logger.info(
            f"Incident "
            f"{result['incident_id']}: "
            f"fused {result['num_views']} "
            f"view(s), "
            f"primary={primary_drone}"
        )

        return result


# --------------------------------------------------------------------------
# ROS integration
# --------------------------------------------------------------------------

def run_ros_node(
    fusion_window_s: float,
):
    """Run the multi-view aggregator as a ROS node."""

    import rospy

    from std_msgs.msg import String

    rospy.init_node(
        "description_report_aggregator",
        anonymous=False,
    )

    aggregator = (
        IncidentReportAggregator(
            fusion_window_s=(
                fusion_window_s
            )
        )
    )

    fused_pub = rospy.Publisher(
        "/description_agent/fused_report",
        String,
        queue_size=10,
    )

    def publish_ready(
        force: bool = False,
    ):

        fused_reports = (
            aggregator.flush_ready(
                force=force
            )
        )

        for report in fused_reports:

            fused_pub.publish(
                String(
                    data=json.dumps(
                        report
                    )
                )
            )

            logger.info(
                f"Published fused report "
                f"for incident "
                f"{report['incident_id']}"
            )

    def _report_cb(
        msg,
    ):

        try:
            report = json.loads(
                msg.data
            )

            aggregator.add_report(
                report
            )

        except (
            json.JSONDecodeError,
            ValueError,
            TypeError,
        ) as exc:

            logger.error(
                f"Invalid view report: "
                f"{exc}"
            )

    def _timer_cb(
        _event,
    ):
        publish_ready(
            force=False
        )

    rospy.Subscriber(
        "/description_agent/view_report",
        String,
        _report_cb,
        queue_size=20,
    )

    # Check frequently enough that the configured fusion window
    # determines latency rather than the timer period.
    rospy.Timer(
        rospy.Duration(
            0.1
        ),
        _timer_cb,
    )

    logger.info(
        "Description report aggregator "
        "listening on "
        "/description_agent/view_report"
    )

    logger.info(
        "Publishing consolidated reports on "
        "/description_agent/fused_report"
    )

    logger.info(
        f"Fusion collection window: "
        f"{fusion_window_s:.2f} s"
    )

    try:
        rospy.spin()

    finally:
        # Flush pending reports during a graceful node shutdown.
        publish_ready(
            force=True
        )


# --------------------------------------------------------------------------
# CLI
# --------------------------------------------------------------------------

def main():

    parser = argparse.ArgumentParser(
        description=(
            "Multi-view description "
            "report aggregator"
        )
    )

    parser.add_argument(
        "--ros",
        action="store_true",
        help=(
            "Run as the ROS report "
            "aggregation node."
        ),
    )

    parser.add_argument(
        "--fusion-window",
        type=float,
        default=1.0,
        help=(
            "Seconds to collect per-view "
            "reports sharing one incident_id "
            "before fusion."
        ),
    )

    args = parser.parse_args()

    if not args.ros:

        parser.error(
            "Use --ros to start the "
            "report aggregator."
        )

    try:
        run_ros_node(
            fusion_window_s=(
                args.fusion_window
            )
        )

    except ImportError:

        logger.error(
            "ROS mode requires rospy."
        )


if __name__ == "__main__":
    main()
